# Generated by Django 5.1.2 on 2024-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("track", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torquedata",
            name="shift",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station1_torque1",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station1_torque2",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station1_torque3",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station2_torque1",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station2_torque2",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station2_torque3",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station3_torque1",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station3_torque2",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station3_torque3",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station4_torque1",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station4_torque2",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="torquedata",
            name="station4_torque3",
            field=models.IntegerField(),
        ),
    ]
